# Generated by Django 2.2.4 on 2020-01-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(default='No description available', max_length=250),
        ),
    ]
